# Generated by Django 5.2.5 on 2025-08-06 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product', max_length=100)),
                ('sku', models.CharField(help_text='Unique Stock Keeping Unit (SKU)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the product')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=3)),
                ('reference_note', models.CharField(blank=True, help_text='Optional reference or reason for transaction', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity affected by this transaction')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockflow.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='stockflow.stocktransaction')),
            ],
            options={
                'unique_together': {('transaction', 'product')},
            },
        ),
    ]
